server.servlet.context-path=/cxtool

spring.application.name=CUITXCPCTool
spring.main.banner-mode=off

spring.config.import=optional:file:./db-secret.properties,\
optional:file:./settings.properties

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./cuit_xcpc;CIPHER=AES;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=${db.file.password} ${db.user.password}
spring.sql.init.schema-locations=classpath:script.sql
spring.sql.init.mode=always
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
logging.pattern.console=[%d{HH:mm:ss}] [%t/%p]: %msg%n
logging.pattern.file=[%d{HH:mm:ss}] [%t/%p]: %msg%n
