server.servlet.context-path=/cxtool
server.port=8080

spring.application.name=CUITXCPCProxy
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cuit_xcpc_tools?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=20051008
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


org.domjudge.host=http://192.168.31.129
org.domjudge.route-path=/dj
org.domjudge.port=80
org.domjudge.contest-id=demo
org.domjudge.account=admin
org.domjudge.password=QK6W1sgT-MGIB2Qz
org.domjudge.print-token=3486dsay89x6786f87aerfbxncmbmghjf

#特殊验证
org.domjudge.use-special-client=true
org.domjudge.nginx-verify-route-path=/dj-verify
org.domjudge.special-client-user-agent=OMSClient
top.jwt.secret-key=5f4dcc3b5aa765d61d8327deb882cf995f4dcc3b5aa765d61d8327deb882cf99
# 时间不用太长，这里只是用于校验浏览器User-Agent
top.jwt.ttl=30000

top.jwt.admin-password=52025202
