-- 队伍信息表
create table if not exists dj_team
(
    exam_number varchar(50) not null primary key,
    team_name   varchar(50) not null,
    school      varchar(50) not null,
    position    varchar(50) not null,
    account     varchar(50) not null,
    password    varchar(50) not null,
    constraint position unique (position)
    );
comment on table dj_team is '存放Domjudge队伍信息的表';

-- 登录任务表
create table if not exists auth_task
(
    exam_num      varchar(50) not null,
    old_client_id varchar(50) not null,
    now_client_id varchar(50) not null,
    id            bigint generated by default as identity primary key,
    create_time   timestamp    not null, -- 修复：DATETIME → TIMESTAMP
    status        varchar(50) not null,
    constraint exam_num foreign key (exam_num) references dj_team (exam_number)
    );
comment on table auth_task is '登录请求队列';

-- 打印任务表
create table if not exists print_task
(
    id          bigint generated by default as identity primary key,
    create_time timestamp     not null, -- 修复：DATETIME → TIMESTAMP
    status      varchar(50)  not null,
    exam_num    varchar(50)  not null,
    file_path   varchar(100) not null,
    file_name   varchar(50) not null,
    constraint team_num foreign key (exam_num) references dj_team (exam_number)
    );
comment on table print_task is '打印请求队列';

-- 队伍客户端表
create table if not exists team_client
(
    exam_num   varchar(50) not null primary key,
    client_id  varchar(50) not null,
    login_time timestamp    not null, -- 修复：DATETIME → TIMESTAMP
    constraint exam_number foreign key (exam_num) references dj_team (exam_number)
    );
comment on table team_client is '查询队伍登录客户端ID的表';